apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendapi
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
      ms: backendapi
  template:
    metadata:
      labels:
        tier: backend
        ms: backendapi
        app: backendapi
    spec:
      containers:
        - name: kubtestbackendapi
          image: pekiaks1.azurecr.io/kubtestbackendapi:latest
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: backendsecret
                  key: ai_key
            - name: ASPNETCORE_URLS
              value: http://*:8080
            - name: DbConnectionString
              valueFrom:
                secretKeyRef:
                  name: backendsecret
                  key: db
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/meta/healthy
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 4
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/meta/ready
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 4
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "96Mi"
              cpu: "125m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapi
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
      ms: frontendapi
  template:
    metadata:
      labels:
        tier: backend
        ms: frontendapi
        app: frontendapi
    spec:
      containers:
        - name: kubtestfrontendapi
          image: pekiaks1.azurecr.io/kubtestfrontendapi:latest
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: backendsecret
                  key: ai_key
            - name: ASPNETCORE_URLS
              value: http://*:8080
            - name: DbConnectionString
              valueFrom:
                secretKeyRef:
                  name: backendsecret
                  key: db
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/meta/healthy
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 4
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/meta/ready
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 4
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "96Mi"
              cpu: "125m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontendapi
spec:
  selector:
    app: frontendapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: backendapi
spec:
  selector:
    app: backendapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer